### ISSUE TITLE
[Question] Setting a range of peer addresses for to use unicast with docker swarm?

### ISSUE THREAD

**Issue by Alqio** [eclipse-cyclonedds/cyclonedds#1442]
I'm deploying a ROS2 application on two machines: one linux and one windows. I'm using docker swarm and it has lots of difficulties with multicast particularly with Windows hosts. I decided to try using unicast instead, but I can't find a guide how one should set up the communication between containers in this case. 

To further complicate the problem, on the windows host, I also possibly need to have a ROS node outside of the docker network that can still communicate with other nodes. However, this is lesser priority so I haven't focused on that yet.

How should I try to achieve this? I tried something like this:

```
<CycloneDDS>
    <Domain id='any'>
        <General>
            <AllowMulticast>false</AllowMulticast>
        </General>
        <Discovery>
            <ParticipantIndex>auto</ParticipantIndex>
            <Peers>
                <Peer address="host.docker.internal"/>
                <Peer address="172.30.128.2"/>
                <Peer address="172.30.128.1"/>
            </Peers>
        </Discovery>
    </Domain>
</CycloneDDS>
```
and using docker-compose
```
version: '2'
services:
  eeg_simulator:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg_simulator/Dockerfile
    env_file:
      - ${ENV_FILE}
    networks:
      mtmsnetwork:
        ipv4_address: 172.30.128.2


  data_batcher:
    build:
      context: .
      dockerfile: ros2_ws/src/data_batcher/Dockerfile
    env_file:
      - ${ENV_FILE}
    privileged: true
    networks:
      mtmsnetwork:
        ipv4_address: 172.30.128.1

networks:
  mtmsnetwork:
    ipam:
      config:
        - subnet: 172.30.0.0/16
```

The nodes can find each other and in theory it works with docker compose, but the ip address change everytime the network is created again and docker swarm does not support setting a static ipv4 address. Is it possible to set a range of ip addresses for peers? Also I'm wondering is if this is the correct approach for this? Is there a way to discover other nodes without specifying ip addresses when using unicast?
