### ISSUE TITLE
Shared memory performance loss over standalone iceoryx

### ISSUE THREAD

**Issue by OscarMrZ** [eclipse-cyclonedds/cyclonedds#2155]
Hello everyone,

I’ve been testing the performance of CycloneDDS with shared memory (SHM) enabled to demonstrate the performance improvements it should provide.

Using the [APEX performance test package](https://gitlab.com/ApexAI/performance_test) and [this dockerfile](https://gitlab.com/ApexAI/performance_test/-/blob/2.3.1/dockerfiles/Dockerfile.CycloneDDS?ref_type=tags) they provide, I runned the following test: 

```yaml
---
experiments:
  -
    com_mean: CycloneDDS
    process_configuration: INTER_PROCESS
    execution_strategy: INTER_THREAD
    sample_transport: 
      - BY_COPY
      - SHARED_MEMORY
      - LOANED_SAMPLES
    msg: Array8m
    pubs: 1
    subs: 
     - 1
     - 2
     - 4
     - 6
     - 8
     - 10
     - 12
     - 14
     - 16
     - 18
     - 20
     - 22
     - 24
     - 26
     - 28
     - 30
     - 32
    rate: 30
    reliability: BEST_EFFORT
    durability: VOLATILE
    history: KEEP_LAST
    history_depth: 5
    max_runtime: 30
    ignore_seconds: 5

```

This test measures the average latency between a publisher publishing an 8MB payload at 30Hz and an increasing number of subscribers, for the [three different available transports](https://gitlab.com/ApexAI/performance_test/-/tree/master/performance_test#:~:text=are%20currently%20implemented%3A-,Eclipse%20Cyclone%20DDS,-Eclipse%20Cyclone%20DDS) available for Cyclone: UDP(copy), SHM, and SHM with loaned samples. The QoS are the ones specified in the YAML. 

These are the results: 

![image](https://github.com/user-attachments/assets/9adfc79d-93ec-4486-8452-fb1cb59f7da0)

I anticipated a substantial performance boost with SHM enabled, regardless of message size or the number of subscribers. However, from the previous plot we can see that: 

1. The latency is "only" reduced by about half compared to the default copy transport, but it remains in the range of tens of milliseconds. This is many orders of magnitude bigger than the results for standalone iceoryx. 
2. Latency increases as the number of subscribers grows. As far as my understanding goes, this could happen with shared memory, but the increase should be marginal. 

For reference, these are the results of the same test with standalone iceoryx, using [this dockerfile](https://gitlab.com/ApexAI/performance_test/-/blob/2.3.1/dockerfiles/Dockerfile.iceoryx?ref_type=tags) as a testing environment. In this case, only the latency for LOANED transport was measured as the other two are not supported in this case. 

![image](https://github.com/user-attachments/assets/11dcea81-2faf-4c87-b9d5-b6a294aa2d75)

Notice that while the latency seems to increase, it is on the order of magnitude of hundredths of milliseconds and the differences are minimal. While I could understand the latency increasing a little bit due to the increased management needed for the subscriber queues, the differences of magnitude escapes my understanding. 

To the best of my knowledge, when enabling shared memory in Cyclone, the behavior should be very similar to the one in the second graph, as it uses iceoryx behind the scenes. Are you guys aware of any reason this could not be the case?

Many thanks in advance!
